version: 2

models:
  - name: new_releases
    description: "New releases on Spotify"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null